version: 0.2
env:
  variables:
    PRX_ECR_REGION: "us-east-1"
    PRX_ECR_REPOSITORY: "testtesttest"
    PRX_CI_PUBLISH: "true"
phases:
  install:
    commands:
      - 'echo "Installing docker-compose..."'
      - 'COMPOSE="https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)" && curl -sL $COMPOSE -o /usr/local/bin/docker-compose'
      - "chmod +x /usr/local/bin/docker-compose"
  build:
    commands:
      - "cd $(ls -d */|head -n 1)"
      - "docker-compose -f docker-compose-ci.yml build"
      - "docker-compose -f docker-compose-ci.yml run play ci"
  post_build:
    commands:
      - 'curl -sO "https://raw.githubusercontent.com/PRX/Infrastructure/master/ci/utility/post_build.sh" && sh post_build.sh'
